package com.castawaysoftware.propertymanager.data;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

/**
 * Pet Class is used to represent a pet that a tenant owns.
 * It tracks basic but necessary information about the pet.
 */
@Entity
public class Pet {

    /**
     * Id of Pet
     * @see <a href="https://docs.oracle.com/javaee/6/api/javax/persistence/GeneratedValue.html">@GeneratedValue</a>
     */
    private @Id
    @GeneratedValue Long id;
    /**
     * Name of Pet
     */
    private String name;
    /**
     * Pet Type, Currently a String. Will change to Enum later
     */
    private String petType;

    /**
     * Create an empty pet
     */
    public Pet() {
    }

    /**
     * Constructor for a pet.
     * <b>ID WILL BE AUTOGENERATED DUE TO "@GeneratedValue" annotation </b>
     * @param name
     * @param petType
     */
    public Pet(String name, String petType) {
        this.name = name;
        this.petType = petType;
    }

    /**
     * get id of Pet
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * set Id of pet to another Long value
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get name of Pet
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Set name of pet to String name
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get type of Pet
     * <em>Will replace in future with Enum</em>
     * @return petType
     */
    public String getPetType() {
        return petType;
    }
    /**
     * set type of Pet
     * <em>Will replace in future with Enum</em>
     * @param  petType
     */
    public void setPetType(String petType) {
        this.petType = petType;
    }

    /**
     * Creates a String Representation of Pet
     * @return String
     */
    @Override
    public String toString() {
        return "Pet{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", petType='" + petType + '\'' +
                '}';
    }
}
