package com.castawaysoftware.propertymanager.data;

import jakarta.persistence.*;

import java.util.List;

/**
 * <b>{@link Property Property.class}</b>
 * This class contains all the information that a property has
 */
@Entity
public class Property {

    /**
     * Id of Property
     * <em>Id is an Generated Value because of the "@GeneratedValue" annotation</em>
     * @see <a href="https://docs.oracle.com/javaee/6/api/javax/persistence/GeneratedValue.html">@GeneratedValue</a>
     */
    private @Id
    @GeneratedValue Long id;

    /**
     * Name of the Property
     */
    private String name;

    /**
     * Address of Property
     */
    @OneToOne(cascade = CascadeType.ALL)
    private Address address;
    /**
     * List of Units attached to Property
     */
    @OneToMany(cascade = CascadeType.ALL)
    private List<Unit> unitList;

    /**
     * Maintenance Limit of the Property
     */
    private int maintenanceLimit;


    /**
     * Empty Property Constructor
     */
    public Property() {
    }

    /**
     * Constructor for creating a Property
     * <em>The ID will be auto-generated by jakarta.persistence</em>
     * @see <a href="https://docs.oracle.com/javaee/6/api/javax/persistence/GeneratedValue.html">@GeneratedValue</a>
     * @param name (String) Name of Property
     * @param address (Address) class of Property
     * @param unitList (List<Unit>) List of all units in the Property
     * @param maintenanceLimit (int) The maintenance limit of the property, prevents over spending
     */
    public Property(String name, Address address, List<Unit> unitList, int maintenanceLimit) {
        this.name = name;
        this.address = address;
        this.unitList = unitList;
        this.maintenanceLimit = maintenanceLimit;

    }

    /**
     *  Get Id of Property
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     *  Set Id of Property
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *  Get name of Property
     */
    public String getName() {
        return name;
    }

    /**
     * Set name of Property
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get Address of Property
     * @return address
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Set Address of Property
     * @param address
     */
    public void setAddress(Address address) {
        this.address = address;
    }

    /**
     * Get List of attached Units for Property
     * @return List<Unit>
     */
    public List<Unit> getUnitList() {
        return unitList;
    }

    /**
     * Set List of Units for Property
     * @param unitList
     */
    public void setUnitList(List<Unit> unitList) {
        this.unitList = unitList;
    }

    /**
     * Get Maintenance Limit of Property
     * @return maintenanceLimit
     */
    public int getMaintenanceLimit() {
        return maintenanceLimit;
    }

    /**
     * Set Maintenance Limit for Property
     * @param maintenanceLimit
     */
    public void setMaintenanceLimit(int maintenanceLimit) {
        this.maintenanceLimit = maintenanceLimit;
    }


    /**
     * Convert Property to String Representation
     * @return String
     */
    @Override
    public String toString() {
        return "Property{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", adress=" + address +
                ", unitList=" + unitList +
                ", maintenanceLimit=" + maintenanceLimit +

                '}';
    }
}
