package com.castawaysoftware.propertymanager.data;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

/**
 * <b>{@link Tenant Tenant.class}</b>
 * This class contains all the information for a tenant lives in a particular
 * {@link Unit Unit.class}
 */
@Entity
public class Tenant {

    /**
     * Id of Tenant
     * @see <a href="https://docs.oracle.com/javaee/6/api/javax/persistence/GeneratedValue.html">@GeneratedValue</a>
     */
    private @Id
    @GeneratedValue Long id;
    /**
     * First Name of Tenant
     */
    private String firstName;
    /**
     * Last Name of Tenant
     */
    private String lastName;
    /**
     * Email of Tenant
     */
    private String email;
    /**
     * Phone Number of Tenant
     */
    private String phoneNumber;

    /**
     * Empty Constructor for Tenant
     */
    public Tenant() {
    }

    /**
     * Constructor to create a Tenant
     * <em>Id will be autogenerated</em>
     * @see <a href="https://docs.oracle.com/javaee/6/api/javax/persistence/GeneratedValue.html">@GeneratedValue</a>
     * @param firstName
     * @param lastName
     * @param email
     * @param phoneNumber
     */
    public Tenant(String firstName, String lastName, String email, String phoneNumber) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phoneNumber = phoneNumber;
    }

    /**
     * Get Id of Tenant
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * Set Id of Tenant
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get First Name of Tenant
     * @return firstName
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Set First Name of Tenant
     * @param firstName
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Get Last Name of Tenant
     * @return lastName
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Set Last Name of Tenant
     * @param lastName
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * get Tenant's Email
     * @return email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Set Tenant's email
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Get Phone Number of Tenant
     * @return phoneNumber
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Set Tenant's Phone Number
     * @param phoneNumber
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Create String Representation of Tenant
     * @return String
     */
    @Override
    public String toString() {
        return "Tenant{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                '}';
    }
}
