package com.castawaysoftware.propertymanager.data;

import jakarta.persistence.*;

import java.util.List;

/**
 * Unit
 * This class contains the basic data for a Unit
 * <ul>
 *     <li>List of Tenants</li>
 *     <li>List of Pets</li>
 * </ul>
 * Later on we will add, rent price, amenities, etc; Currently not part of the MVP
 */
@Entity
public class Unit {

    /**
     * Id of Unit
     * @see <a href="https://docs.oracle.com/javaee/6/api/javax/persistence/GeneratedValue.html">@GeneratedValue</a>
     */
    private @Id
    @GeneratedValue Long id;
    /**
     * Unit Identifier ex: 10, 3234, A;
     */
    private String unitIdentifier;
    /**
     * List of Tenants in unit
     */
    @OneToMany(cascade = CascadeType.ALL)
    private List<Tenant> tenantList;
    /**
     * List of pets in unit
     */
    @OneToMany(cascade = CascadeType.ALL)
    private List<Pet> petList;

    /**
     * Empty Constructor
     */
    public Unit() {
    }

    /**
     * Constructor to Create Unit
     * <em>ID will be autogenerated</em>
     * @param unitIdentifier
     * @param tenantList
     * @param petList
     */
    public Unit(String unitIdentifier, List<Tenant> tenantList, List<Pet> petList) {
        this.unitIdentifier = unitIdentifier;
        this.tenantList = tenantList;
        this.petList = petList;
    }

    /**
     * Get Unit Id
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * set Unit Id
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get Unit Identifier
     * @return unitIdentifier
     */
    public String getUnitIdentifier() {
        return unitIdentifier;
    }

    /**\
     * set Unit Identifier
     * @param unitIdentifier
     */
    public void setUnitIdentifier(String unitIdentifier) {
        this.unitIdentifier = unitIdentifier;
    }

    /**
     * Get List of Tenants for Unit
     * @return tenantList
     */
    public List<Tenant> getTenantList() {
        return tenantList;
    }

    /**
     * Set List of Tenants for Unit
     * @param tenantList
     */
    public void setTenantList(List<Tenant> tenantList) {
        this.tenantList = tenantList;
    }

    /**
     * Get List of Pets for Unit
     * @return petList
     */
    public List<Pet> getPetList() {
        return petList;
    }

    /**
     * Set List of Pets for Unit
     * @param petList
     */
    public void setPetList(List<Pet> petList) {
        this.petList = petList;
    }

    /**
     * Create String representation of Unit Object
     * @return String
     */
    @Override
    public String toString() {
        return "Unit{" +
                "id=" + id +
                ", unitIdentifier='" + unitIdentifier + '\'' +
                ", tenantList=" + tenantList +
                ", petList=" + petList +
                '}';
    }
}
