package com.castawaysoftware.propertymanager.data;

import jakarta.persistence.*;

import java.util.Collection;
import java.util.List;

/**
 * Unit
 * This class contains the basic data for a Unit
 * <ul>
 *     <li>List of Tenants</li>
 *     <li>List of Pets</li>
 * </ul>
 * Later on we will add, rent price, amenities, etc; Currently not part of the MVP
 */
@Entity
public class Unit {

    /**
     * Id of Unit
     * @see <a href="https://docs.oracle.com/javaee/6/api/javax/persistence/GeneratedValue.html">@GeneratedValue</a>
     */
    private @Id
    @GeneratedValue Long id;
    /**
     * Unit Identifier ex: 10, 3234, A;
     */
    private String unitIdentifier;
    /**
     * List of Tenants in unit
     */
    @OneToMany(cascade = CascadeType.ALL)
    private List<Tenant> tenantList;
    /**
     * List of pets in unit
     */
    @OneToMany(cascade = CascadeType.ALL)
    private List<Pet> petList;

    private boolean isVacant;
    private boolean allowsPets;

    private int numberOfBeds;

    private double numberOfBaths;

    private int squareFeet;


    private List<String> amenities;

    private List<String> appliances;

    private int monthlyRent;

    private int applicationFee;

    private int securityDeposit;

    private String unitDescription;

    @ElementCollection
    @OneToMany(cascade = CascadeType.ALL)
    @CollectionTable(name="listOfWorkOrders")
    private List<WorkOrder> workOrderList;

    /**
     * Empty Constructor
     */
    public Unit() {
    }

    public Unit(String unitIdentifier, List<Tenant> tenantList, List<Pet> petList) {
        this.unitIdentifier = unitIdentifier;
        this.tenantList = tenantList;
        this.petList = petList;
    }

    /**
     * Constructor to Create Unit
     * <em>ID will be autogenerated</em>
     * @param unitIdentifier
     * @param tenantList
     * @param petList
     */

    public Unit(String unitIdentifier, List<Tenant> tenantList, List<Pet> petList, boolean isVacant, boolean allowsPets, int numberOfBeds, double numberOfBaths, int squareFeet, List<String> amenities, List<String> appliances, int monthlyRent, int applicationFee, int securityDeposit, String unitDescription, List<WorkOrder> workOrderList) {
        this.unitIdentifier = unitIdentifier;
        this.tenantList = tenantList;
        this.petList = petList;
        this.isVacant = isVacant;
        this.allowsPets = allowsPets;
        this.numberOfBeds = numberOfBeds;
        this.numberOfBaths = numberOfBaths;
        this.squareFeet = squareFeet;
        this.amenities = amenities;
        this.appliances = appliances;
        this.monthlyRent = monthlyRent;
        this.applicationFee = applicationFee;
        this.securityDeposit = securityDeposit;
        this.unitDescription = unitDescription;
        this.workOrderList = workOrderList;
    }

    /**
     * Created a unit with only unit identifer
     * @param unitIdentifier
     */
    public Unit(String unitIdentifier) {
        this.unitIdentifier = unitIdentifier;
    }

    /**
     * Get Unit Id
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * set Unit Id
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get Unit Identifier
     * @return unitIdentifier
     */
    public String getUnitIdentifier() {
        return unitIdentifier;
    }

    /**\
     * set Unit Identifier
     * @param unitIdentifier
     */
    public void setUnitIdentifier(String unitIdentifier) {
        this.unitIdentifier = unitIdentifier;
    }

    /**
     * Get List of Tenants for Unit
     * @return tenantList
     */
    public List<Tenant> getTenantList() {
        return tenantList;
    }

    /**
     * Set List of Tenants for Unit
     * @param tenantList
     */
    public void setTenantList(List<Tenant> tenantList) {
        this.tenantList = tenantList;
    }

    /**
     * Get List of Pets for Unit
     * @return petList
     */
    public List<Pet> getPetList() {
        return petList;
    }

    /**
     * Set List of Pets for Unit
     * @param petList
     */
    public void setPetList(List<Pet> petList) {
        this.petList = petList;
    }

    public boolean isVacant() {
        return isVacant;
    }

    public void setVacant(boolean vacant) {
        isVacant = vacant;
    }

    public boolean isAllowsPets() {
        return allowsPets;
    }

    public void setAllowsPets(boolean allowsPets) {
        this.allowsPets = allowsPets;
    }

    public int getNumberOfBeds() {
        return numberOfBeds;
    }

    public void setNumberOfBeds(int numberOfBeds) {
        this.numberOfBeds = numberOfBeds;
    }

    public double getNumberOfBaths() {
        return numberOfBaths;
    }

    public void setNumberOfBaths(double numberOfBaths) {
        this.numberOfBaths = numberOfBaths;
    }

    public int getSquareFeet() {
        return squareFeet;
    }

    public void setSquareFeet(int squareFeet) {
        this.squareFeet = squareFeet;
    }

    public List<String> getAmenities() {
        return amenities;
    }

    public void setAmenities(List<String> amenities) {
        this.amenities = amenities;
    }

    public List<String> getAppliances() {
        return appliances;
    }

    public void setAppliances(List<String> appliances) {
        this.appliances = appliances;
    }

    public int getMonthlyRent() {
        return monthlyRent;
    }

    public void setMonthlyRent(int monthlyRent) {
        this.monthlyRent = monthlyRent;
    }

    public int getApplicationFee() {
        return applicationFee;
    }

    public void setApplicationFee(int applicationFee) {
        this.applicationFee = applicationFee;
    }

    public int getSecurityDeposit() {
        return securityDeposit;
    }

    public void setSecurityDeposit(int securityDeposit) {
        this.securityDeposit = securityDeposit;
    }

    public String getUnitDescription() {
        return unitDescription;
    }

    public void setUnitDescription(String unitDescription) {
        this.unitDescription = unitDescription;
    }

    public List<WorkOrder> getWorkOrderList() {
        return workOrderList;
    }

    public void setWorkOrderList(List<WorkOrder> workOrderList) {
        this.workOrderList = workOrderList;
    }

    /**
     * Create String representation of Unit Object
     * @return String
     */
    @Override
    public String toString() {
        return "Unit{" +
                "id=" + id +
                ", unitIdentifier='" + unitIdentifier + '\'' +
                ", tenantList=" + tenantList +
                ", petList=" + petList +
                ", isVacant=" + isVacant +
                ", allowsPets=" + allowsPets +
                ", numberOfBeds=" + numberOfBeds +
                ", numberOfBaths=" + numberOfBaths +
                ", squareFeet=" + squareFeet +
                ", amenities=" + amenities +
                ", appliances=" + appliances +
                ", monthlyRent=" + monthlyRent +
                ", applicationFee=" + applicationFee +
                ", securityDeposit=" + securityDeposit +
                ", unitDescription='" + unitDescription + '\'' +
                '}';
    }
}
